package com.example.a30dayapp.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF5C631C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE1E993)
val onPrimaryContainerLight = Color(0xFF1A1D00)
val secondaryLight = Color(0xFF206487)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC6E7FF)
val onSecondaryContainerLight = Color(0xFF001E2D)
val tertiaryLight = Color(0xFF3C665A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBEECDC)
val onTertiaryContainerLight = Color(0xFF002019)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFCFAEC)
val onBackgroundLight = Color(0xFF1C1C14)
val surfaceLight = Color(0xFFFCFAEC)
val onSurfaceLight = Color(0xFF1C1C14)
val surfaceVariantLight = Color(0xFFE5E3D2)
val onSurfaceVariantLight = Color(0xFF47483B)
val outlineLight = Color(0xFF787869)
val outlineVariantLight = Color(0xFFC8C7B7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313128)
val inverseOnSurfaceLight = Color(0xFFF3F1E4)
val inversePrimaryLight = Color(0xFFC5CC7A)
val surfaceDimLight = Color(0xFFDCDACE)
val surfaceBrightLight = Color(0xFFFCFAEC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F4E7)
val surfaceContainerLight = Color(0xFFF0EEE1)
val surfaceContainerHighLight = Color(0xFFEBE8DC)
val surfaceContainerHighestLight = Color(0xFFE5E3D6)

val primaryDark = Color(0xFFC5CC7A)
val onPrimaryDark = Color(0xFF2F3300)
val primaryContainerDark = Color(0xFF454B04)
val onPrimaryContainerDark = Color(0xFFE1E993)
val secondaryDark = Color(0xFF92CEF5)
val onSecondaryDark = Color(0xFF00344B)
val secondaryContainerDark = Color(0xFF004C6B)
val onSecondaryContainerDark = Color(0xFFC6E7FF)
val tertiaryDark = Color(0xFFA2D0C0)
val onTertiaryDark = Color(0xFF07372C)
val tertiaryContainerDark = Color(0xFF234E42)
val onTertiaryContainerDark = Color(0xFFBEECDC)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF13140C)
val onBackgroundDark = Color(0xFFE5E3D6)
val surfaceDark = Color(0xFF13140C)
val onSurfaceDark = Color(0xFFE5E3D6)
val surfaceVariantDark = Color(0xFF47483B)
val onSurfaceVariantDark = Color(0xFFC8C7B7)
val outlineDark = Color(0xFF929182)
val outlineVariantDark = Color(0xFF47483B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E3D6)
val inverseOnSurfaceDark = Color(0xFF313128)
val inversePrimaryDark = Color(0xFF5C631C)
val surfaceDimDark = Color(0xFF13140C)
val surfaceBrightDark = Color(0xFF3A3A31)
val surfaceContainerLowestDark = Color(0xFF0E0F08)
val surfaceContainerLowDark = Color(0xFF1C1C14)
val surfaceContainerDark = Color(0xFF202018)
val surfaceContainerHighDark = Color(0xFF2A2A22)
val surfaceContainerHighestDark = Color(0xFF35352D)







